# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 */7 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        DOCKER_FILE: [
          docker/centos-7/Dockerfile,
          docker/centos-stream8/Dockerfile,
          docker/centos-stream9/Dockerfile,
          docker/fedora-31/Dockerfile,
          docker/fedora-32/Dockerfile,
          docker/fedora-33/Dockerfile,
          docker/fedora-34/Dockerfile,
          docker/fedora-35/Dockerfile,
          docker/fedora-36/Dockerfile,
          docker/rocky-8/Dockerfile,
          docker/rocky-8.5/Dockerfile,
          docker/rocky-9/Dockerfile,
          docker/ubuntu-18.04-lts/Dockerfile,
          docker/ubuntu-20.04-lts/Dockerfile,
          docker/ubuntu-22.04-lts/Dockerfile,
        ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare the build container
        env:
          DOCKER_FILE: ${{ matrix.DOCKER_FILE }}
        run: |
          docker build --rm -f ${DOCKER_FILE} --build-arg RUNUID=$UID -t ikforth-build:latest .
          docker run --rm -i -v $PWD:/opt/ikforth ikforth-build:latest -c "scons -c linux all && scons -c win32 all"

      - name: Build IKForth
        run: |
          export GIT_DESC=`git describe --tags --always --abbrev=8 --dirty=-wip`
          ./docker/build-ci.sh
